// Mocks generated by Mockito 5.4.6 from annotations
// in ts_parking/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i40;
import 'package:ts_parking/app/core/errors/failures.dart' as _i6;
import 'package:ts_parking/app/core/services/stripe_card_token_service.dart'
    as _i39;
import 'package:ts_parking/app/data/models/paginated_response.dart' as _i20;
import 'package:ts_parking/app/domain/entities/create_subscription_response_entity.dart'
    as _i27;
import 'package:ts_parking/app/domain/entities/invoice_entity.dart' as _i29;
import 'package:ts_parking/app/domain/entities/login_response.dart' as _i7;
import 'package:ts_parking/app/domain/entities/notification_entity.dart'
    as _i32;
import 'package:ts_parking/app/domain/entities/payment_transaction_entity.dart'
    as _i13;
import 'package:ts_parking/app/domain/entities/pricing_plan_entity.dart'
    as _i22;
import 'package:ts_parking/app/domain/entities/settings_entity.dart' as _i35;
import 'package:ts_parking/app/domain/entities/slot_entity.dart' as _i23;
import 'package:ts_parking/app/domain/entities/subscription_entity.dart'
    as _i26;
import 'package:ts_parking/app/domain/entities/user_card_entity.dart' as _i12;
import 'package:ts_parking/app/domain/entities/user_entity.dart' as _i11;
import 'package:ts_parking/app/domain/entities/vehicle_charge_entity.dart'
    as _i37;
import 'package:ts_parking/app/domain/entities/vehicle_entity.dart' as _i16;
import 'package:ts_parking/app/domain/entities/vehicle_type_entity.dart'
    as _i15;
import 'package:ts_parking/app/domain/entities/yard_entity.dart' as _i21;
import 'package:ts_parking/app/domain/entities/zone_entity.dart' as _i24;
import 'package:ts_parking/app/domain/params/add_vehicle_params.dart' as _i17;
import 'package:ts_parking/app/domain/params/create_subscription_params.dart'
    as _i28;
import 'package:ts_parking/app/domain/params/driver_params.dart' as _i8;
import 'package:ts_parking/app/domain/params/notification_params.dart' as _i33;
import 'package:ts_parking/app/domain/params/otp_params.dart' as _i9;
import 'package:ts_parking/app/domain/params/pay_invoice_params.dart' as _i30;
import 'package:ts_parking/app/domain/params/pay_overstay_charge_params.dart'
    as _i38;
import 'package:ts_parking/app/domain/params/register_params.dart' as _i10;
import 'package:ts_parking/app/domain/params/update_vehicle_params.dart'
    as _i18;
import 'package:ts_parking/app/domain/repositories/auth_repository.dart' as _i4;
import 'package:ts_parking/app/domain/repositories/notification_repository.dart'
    as _i31;
import 'package:ts_parking/app/domain/repositories/payment_method_repository.dart'
    as _i3;
import 'package:ts_parking/app/domain/repositories/settings_repository.dart'
    as _i34;
import 'package:ts_parking/app/domain/repositories/subscription_repository.dart'
    as _i25;
import 'package:ts_parking/app/domain/repositories/vehicle_charge_repository.dart'
    as _i36;
import 'package:ts_parking/app/domain/repositories/vehicle_repository.dart'
    as _i14;
import 'package:ts_parking/app/domain/repositories/yard_repository.dart'
    as _i19;
import 'package:ts_parking/app/domain/usecases/add_card_usecase.dart' as _i41;
import 'package:ts_parking/app/domain/usecases/delete_card_usecase.dart'
    as _i42;
import 'package:ts_parking/app/domain/usecases/get_transactions_usecase.dart'
    as _i43;
import 'package:ts_parking/app/domain/usecases/get_user_cards_usecase.dart'
    as _i44;
import 'package:ts_parking/app/domain/usecases/logout_usecase.dart' as _i46;
import 'package:ts_parking/app/domain/usecases/set_default_card_usecase.dart'
    as _i45;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaymentMethodRepository_1 extends _i1.SmartFake
    implements _i3.PaymentMethodRepository {
  _FakePaymentMethodRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthRepository_2 extends _i1.SmartFake
    implements _i4.AuthRepository {
  _FakeAuthRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.LoginResponse>> login(
    _i8.LoginParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [params]),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, _i7.LoginResponse>>.value(
                  _FakeEither_0<_i6.Failure, _i7.LoginResponse>(
                    this,
                    Invocation.method(#login, [params]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i7.LoginResponse>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, String>> sendOtp(
    _i9.SendOtpParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendOtp, [params]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, String>>.value(
              _FakeEither_0<_i6.Failure, String>(
                this,
                Invocation.method(#sendOtp, [params]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, String>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.LoginResponse>> verifyOtp(
    _i9.VerifyOtpParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [params]),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, _i7.LoginResponse>>.value(
                  _FakeEither_0<_i6.Failure, _i7.LoginResponse>(
                    this,
                    Invocation.method(#verifyOtp, [params]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i7.LoginResponse>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> register(
    _i10.RegisterParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [params]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#register, [params]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> deleteAccount(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, [userId]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#deleteAccount, [userId]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i11.UserEntity?>> getCachedUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedUser, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, _i11.UserEntity?>>.value(
                  _FakeEither_0<_i6.Failure, _i11.UserEntity?>(
                    this,
                    Invocation.method(#getCachedUser, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i11.UserEntity?>>);
}

/// A class which mocks [PaymentMethodRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentMethodRepository extends _i1.Mock
    implements _i3.PaymentMethodRepository {
  MockPaymentMethodRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> addCard({
    required String? paymentToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addCard, [], {#paymentToken: paymentToken}),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#addCard, [], {#paymentToken: paymentToken}),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i12.UserCardEntity>>>
  getUserCards() =>
      (super.noSuchMethod(
            Invocation.method(#getUserCards, []),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, List<_i12.UserCardEntity>>
                >.value(
                  _FakeEither_0<_i6.Failure, List<_i12.UserCardEntity>>(
                    this,
                    Invocation.method(#getUserCards, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i12.UserCardEntity>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i13.PaymentTransactionEntity>>>
  getTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#getTransactions, []),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, List<_i13.PaymentTransactionEntity>>
                >.value(
                  _FakeEither_0<
                    _i6.Failure,
                    List<_i13.PaymentTransactionEntity>
                  >(this, Invocation.method(#getTransactions, [])),
                ),
          )
          as _i5.Future<
            _i2.Either<_i6.Failure, List<_i13.PaymentTransactionEntity>>
          >);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> setDefaultCard({
    required String? cardId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setDefaultCard, [], {#cardId: cardId}),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#setDefaultCard, [], {#cardId: cardId}),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> deleteCard({
    required String? cardId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCard, [], {#cardId: cardId}),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#deleteCard, [], {#cardId: cardId}),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [IVehicleRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIVehicleRepository extends _i1.Mock
    implements _i14.IVehicleRepository {
  MockIVehicleRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i15.VehicleTypeEntity>>>
  getVehicleTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getVehicleTypes, []),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, List<_i15.VehicleTypeEntity>>
                >.value(
                  _FakeEither_0<_i6.Failure, List<_i15.VehicleTypeEntity>>(
                    this,
                    Invocation.method(#getVehicleTypes, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i15.VehicleTypeEntity>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i16.VehicleEntity>>> getVehicles() =>
      (super.noSuchMethod(
            Invocation.method(#getVehicles, []),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, List<_i16.VehicleEntity>>
                >.value(
                  _FakeEither_0<_i6.Failure, List<_i16.VehicleEntity>>(
                    this,
                    Invocation.method(#getVehicles, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i16.VehicleEntity>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i16.VehicleEntity>> addVehicle(
    _i17.AddVehicleParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addVehicle, [params]),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, _i16.VehicleEntity>>.value(
                  _FakeEither_0<_i6.Failure, _i16.VehicleEntity>(
                    this,
                    Invocation.method(#addVehicle, [params]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i16.VehicleEntity>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i16.VehicleEntity>> updateVehicle(
    _i18.UpdateVehicleParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateVehicle, [params]),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, _i16.VehicleEntity>>.value(
                  _FakeEither_0<_i6.Failure, _i16.VehicleEntity>(
                    this,
                    Invocation.method(#updateVehicle, [params]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i16.VehicleEntity>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> deleteVehicle(String? vehicleId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteVehicle, [vehicleId]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#deleteVehicle, [vehicleId]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [IYardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIYardRepository extends _i1.Mock implements _i19.IYardRepository {
  MockIYardRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i20.PaginatedResponse<_i21.YardEntity>>>
  getYards({int? page = 1, int? limit = 20}) =>
      (super.noSuchMethod(
            Invocation.method(#getYards, [], {#page: page, #limit: limit}),
            returnValue:
                _i5.Future<
                  _i2.Either<
                    _i6.Failure,
                    _i20.PaginatedResponse<_i21.YardEntity>
                  >
                >.value(
                  _FakeEither_0<
                    _i6.Failure,
                    _i20.PaginatedResponse<_i21.YardEntity>
                  >(
                    this,
                    Invocation.method(#getYards, [], {
                      #page: page,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i5.Future<
            _i2.Either<_i6.Failure, _i20.PaginatedResponse<_i21.YardEntity>>
          >);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i22.PricingPlanEntity>>>
  getPricingPlans() =>
      (super.noSuchMethod(
            Invocation.method(#getPricingPlans, []),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, List<_i22.PricingPlanEntity>>
                >.value(
                  _FakeEither_0<_i6.Failure, List<_i22.PricingPlanEntity>>(
                    this,
                    Invocation.method(#getPricingPlans, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i22.PricingPlanEntity>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i20.PaginatedResponse<_i23.SlotEntity>>>
  getYardSlots({required String? yardId, int? page = 1, int? limit = 500}) =>
      (super.noSuchMethod(
            Invocation.method(#getYardSlots, [], {
              #yardId: yardId,
              #page: page,
              #limit: limit,
            }),
            returnValue:
                _i5.Future<
                  _i2.Either<
                    _i6.Failure,
                    _i20.PaginatedResponse<_i23.SlotEntity>
                  >
                >.value(
                  _FakeEither_0<
                    _i6.Failure,
                    _i20.PaginatedResponse<_i23.SlotEntity>
                  >(
                    this,
                    Invocation.method(#getYardSlots, [], {
                      #yardId: yardId,
                      #page: page,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i5.Future<
            _i2.Either<_i6.Failure, _i20.PaginatedResponse<_i23.SlotEntity>>
          >);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i24.ZoneEntity>>> getYardZones(
    String? yardId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getYardZones, [yardId]),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, List<_i24.ZoneEntity>>
                >.value(
                  _FakeEither_0<_i6.Failure, List<_i24.ZoneEntity>>(
                    this,
                    Invocation.method(#getYardZones, [yardId]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i24.ZoneEntity>>>);
}

/// A class which mocks [SubscriptionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionRepository extends _i1.Mock
    implements _i25.SubscriptionRepository {
  MockSubscriptionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<
    _i2.Either<_i6.Failure, _i20.PaginatedResponse<_i26.SubscriptionEntity>>
  >
  getSubscriptions({int? page = 1, int? limit = 6}) =>
      (super.noSuchMethod(
            Invocation.method(#getSubscriptions, [], {
              #page: page,
              #limit: limit,
            }),
            returnValue:
                _i5.Future<
                  _i2.Either<
                    _i6.Failure,
                    _i20.PaginatedResponse<_i26.SubscriptionEntity>
                  >
                >.value(
                  _FakeEither_0<
                    _i6.Failure,
                    _i20.PaginatedResponse<_i26.SubscriptionEntity>
                  >(
                    this,
                    Invocation.method(#getSubscriptions, [], {
                      #page: page,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i5.Future<
            _i2.Either<
              _i6.Failure,
              _i20.PaginatedResponse<_i26.SubscriptionEntity>
            >
          >);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i27.CreateSubscriptionResponseEntity>>
  createSubscriptions(_i28.CreateSubscriptionParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#createSubscriptions, [params]),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, _i27.CreateSubscriptionResponseEntity>
                >.value(
                  _FakeEither_0<
                    _i6.Failure,
                    _i27.CreateSubscriptionResponseEntity
                  >(this, Invocation.method(#createSubscriptions, [params])),
                ),
          )
          as _i5.Future<
            _i2.Either<_i6.Failure, _i27.CreateSubscriptionResponseEntity>
          >);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i29.InvoiceEntity>> payInvoice(
    _i30.PayInvoiceParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#payInvoice, [params]),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, _i29.InvoiceEntity>>.value(
                  _FakeEither_0<_i6.Failure, _i29.InvoiceEntity>(
                    this,
                    Invocation.method(#payInvoice, [params]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i29.InvoiceEntity>>);

  @override
  _i5.Future<
    _i2.Either<_i6.Failure, _i20.PaginatedResponse<_i29.InvoiceEntity>>
  >
  getInvoices({int? page = 1, int? limit = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#getInvoices, [], {#page: page, #limit: limit}),
            returnValue:
                _i5.Future<
                  _i2.Either<
                    _i6.Failure,
                    _i20.PaginatedResponse<_i29.InvoiceEntity>
                  >
                >.value(
                  _FakeEither_0<
                    _i6.Failure,
                    _i20.PaginatedResponse<_i29.InvoiceEntity>
                  >(
                    this,
                    Invocation.method(#getInvoices, [], {
                      #page: page,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i5.Future<
            _i2.Either<_i6.Failure, _i20.PaginatedResponse<_i29.InvoiceEntity>>
          >);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i29.InvoiceEntity>> getInvoiceById(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getInvoiceById, [id]),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, _i29.InvoiceEntity>>.value(
                  _FakeEither_0<_i6.Failure, _i29.InvoiceEntity>(
                    this,
                    Invocation.method(#getInvoiceById, [id]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i29.InvoiceEntity>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> deleteSubscription(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSubscription, [id]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#deleteSubscription, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [INotificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockINotificationRepository extends _i1.Mock
    implements _i31.INotificationRepository {
  MockINotificationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<
    _i2.Either<_i6.Failure, _i20.PaginatedResponse<_i32.NotificationEntity>>
  >
  getNotifications(_i33.NotificationFilterParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#getNotifications, [params]),
            returnValue:
                _i5.Future<
                  _i2.Either<
                    _i6.Failure,
                    _i20.PaginatedResponse<_i32.NotificationEntity>
                  >
                >.value(
                  _FakeEither_0<
                    _i6.Failure,
                    _i20.PaginatedResponse<_i32.NotificationEntity>
                  >(this, Invocation.method(#getNotifications, [params])),
                ),
          )
          as _i5.Future<
            _i2.Either<
              _i6.Failure,
              _i20.PaginatedResponse<_i32.NotificationEntity>
            >
          >);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> markAsRead(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [id]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#markAsRead, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> markAllAsRead() =>
      (super.noSuchMethod(
            Invocation.method(#markAllAsRead, []),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#markAllAsRead, []),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, int>> getUnreadCount() =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadCount, []),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, int>>.value(
              _FakeEither_0<_i6.Failure, int>(
                this,
                Invocation.method(#getUnreadCount, []),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, int>>);
}

/// A class which mocks [ISettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockISettingsRepository extends _i1.Mock
    implements _i34.ISettingsRepository {
  MockISettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i35.SettingsEntity>> getSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getSettings, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, _i35.SettingsEntity>>.value(
                  _FakeEither_0<_i6.Failure, _i35.SettingsEntity>(
                    this,
                    Invocation.method(#getSettings, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i35.SettingsEntity>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> uploadProfileImage(
    String? imagePath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfileImage, [imagePath]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#uploadProfileImage, [imagePath]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [IVehicleChargeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIVehicleChargeRepository extends _i1.Mock
    implements _i36.IVehicleChargeRepository {
  MockIVehicleChargeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<
    _i2.Either<_i6.Failure, _i20.PaginatedResponse<_i37.VehicleChargeEntity>>
  >
  getVehicleCharges({int? page = 1, int? limit = 20}) =>
      (super.noSuchMethod(
            Invocation.method(#getVehicleCharges, [], {
              #page: page,
              #limit: limit,
            }),
            returnValue:
                _i5.Future<
                  _i2.Either<
                    _i6.Failure,
                    _i20.PaginatedResponse<_i37.VehicleChargeEntity>
                  >
                >.value(
                  _FakeEither_0<
                    _i6.Failure,
                    _i20.PaginatedResponse<_i37.VehicleChargeEntity>
                  >(
                    this,
                    Invocation.method(#getVehicleCharges, [], {
                      #page: page,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i5.Future<
            _i2.Either<
              _i6.Failure,
              _i20.PaginatedResponse<_i37.VehicleChargeEntity>
            >
          >);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> payOverstayCharge(
    _i38.PayOverstayChargeParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#payOverstayCharge, [params]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#payOverstayCharge, [params]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [StripeCardTokenService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStripeCardTokenService extends _i1.Mock
    implements _i39.StripeCardTokenService {
  MockStripeCardTokenService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> createCardPaymentMethodId({String? cardholderName}) =>
      (super.noSuchMethod(
            Invocation.method(#createCardPaymentMethodId, [], {
              #cardholderName: cardholderName,
            }),
            returnValue: _i5.Future<String>.value(
              _i40.dummyValue<String>(
                this,
                Invocation.method(#createCardPaymentMethodId, [], {
                  #cardholderName: cardholderName,
                }),
              ),
            ),
          )
          as _i5.Future<String>);
}

/// A class which mocks [AddCardUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddCardUsecase extends _i1.Mock implements _i41.AddCardUsecase {
  MockAddCardUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PaymentMethodRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePaymentMethodRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.PaymentMethodRepository);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> execute(String? paymentToken) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [paymentToken]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#execute, [paymentToken]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [DeleteCardUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteCardUsecase extends _i1.Mock implements _i42.DeleteCardUsecase {
  MockDeleteCardUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PaymentMethodRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePaymentMethodRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.PaymentMethodRepository);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> execute(String? cardId) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [cardId]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#execute, [cardId]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [GetTransactionsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTransactionsUsecase extends _i1.Mock
    implements _i43.GetTransactionsUsecase {
  MockGetTransactionsUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PaymentMethodRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePaymentMethodRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.PaymentMethodRepository);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i13.PaymentTransactionEntity>>>
  execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, List<_i13.PaymentTransactionEntity>>
                >.value(
                  _FakeEither_0<
                    _i6.Failure,
                    List<_i13.PaymentTransactionEntity>
                  >(this, Invocation.method(#execute, [])),
                ),
          )
          as _i5.Future<
            _i2.Either<_i6.Failure, List<_i13.PaymentTransactionEntity>>
          >);
}

/// A class which mocks [GetUserCardsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserCardsUsecase extends _i1.Mock
    implements _i44.GetUserCardsUsecase {
  MockGetUserCardsUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PaymentMethodRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePaymentMethodRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.PaymentMethodRepository);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i12.UserCardEntity>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, List<_i12.UserCardEntity>>
                >.value(
                  _FakeEither_0<_i6.Failure, List<_i12.UserCardEntity>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i12.UserCardEntity>>>);
}

/// A class which mocks [SetDefaultCardUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetDefaultCardUsecase extends _i1.Mock
    implements _i45.SetDefaultCardUsecase {
  MockSetDefaultCardUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PaymentMethodRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePaymentMethodRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.PaymentMethodRepository);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> execute(String? cardId) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [cardId]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#execute, [cardId]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [LogoutUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUsecase extends _i1.Mock implements _i46.LogoutUsecase {
  MockLogoutUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.AuthRepository);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#execute, []),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);
}
